---
title: "Approved projects"
---

```{r setup}
#| include: false
library(tidyverse)
library(fs)
```

```{r}
#| echo: false
#| results: asis
project_description_template <- "
\n
## {id}: {project_title}
\n
{project_description}
\n
- Lead author: {full_name}, {job_position} at {affiliation}
- GitHub repository: [github.com/steno-aarhus/{id}](https://github.com/steno-aarhus/{id})
{doi}
"

format_doi_as_md_list <- function(data) {
  doi_as_md_list <- data |>
    dplyr::select(tidyselect::starts_with("doi")) |>
    tidyr::pivot_longer(
      cols = tidyselect::everything(),
      names_to = "type", values_to = "doi"
    ) |>
    tidyr::drop_na() |>
    dplyr::mutate(
      type = stringr::str_remove(type, "doi_") |>
        stringr::str_to_sentence(),
      doi = glue::glue("- {type}: [{doi}](https://doi.org/{doi})")
    ) |> 
    dplyr::pull(doi) |> 
    stringr::str_c(collapse = "\n")
  data |> 
    dplyr::mutate(doi = doi_as_md_list)
}

admin_read_projects() |>
  map(\(project) format_doi_as_md_list(project)) |>
  map(\(project) glue::glue_data(project, project_description_template)) %>%
  walk(~ cat(.x, sep = "\n\n"))
```
