---
title: "workflow"
---

For the most part, follow the todo items in your own project
repository's tracking Issue. Here we describe the next steps to do after
getting setup on the RAP.

## 4. Upload study protocol on osf.io and add link to project on Trello

*in R using UKB aid R package* We have decided that all projects should
include a pre-registered protocol of the study. This is to encourage
more open research and, because there are so many projects being
conducted in the UKB, to ensure that you can later claim to have been
first with the research idea, if necessary. This is also good research
practice and forces one to carefully think about the study before
conducting analyses.

In addition to the protocol, we encourage that most will also include a
detailed statistical analysis plan. This also makes it easier to perform
the analysis, as there is a clear direction from the beginning. The
analysis plan should be of a similar detail as how you would describe
your analysis in a manuscript.

Note that as an employee at the Region or Aarhus University you have
access to get your analysis plan reviewed by a statistician as part of
the [CONNECT
initiative](http://www.fagperson.auh.dk/afdelinger/connect-center-for-kliniske-genomiske-data/om-connect/).
If you are doing new or more complicated analyses, we encourage you to
use this offer.

The protocol can be written in R markdown using the template provided in
the ukbAid R package. At this point, you will download the [ukbAid R
package](https://github.com/steno-aarhus/ukbAid) on your own (local)
computer.
