---
title: "workflow"
---

-   Workflow:

    -   RAP
    -   Important notes: DON'T SAVE Data
    -   General research

Updated: 11-01-2023

Updated: 11-01-2023

# Overview

This is the current workflow of how you start with an idea for a project
you want to conduct using data from UK Biobank (UKB). This process is
subject to changes.

## The process

1.  Upload project proposal on Trello under 'Project proposals'
2.  Get acceptance of the proposal from the organizing committee
3.  Add project description to Trello under 'Ongoing projects'
4.  Upload study protocol on osf.io and add link to project on Trello
5.  Statistical analyses completed
6.  Get analysis code reviewed
7.  Upload study manuscript to pre-print server and add link on Trello
8.  Add link to manuscript on Trello once published
9.  Data documentation

# Details

## 1. Upload project proposal on Trello under 'Project proposals'

*in Trello* Use the template and fill in:

-   aim
-   population
-   intervention/exposure
-   comparison
-   outcome

For this stage you do not have to be very detailed about the
description. This is just to give an overview of what your project is
about. We recommend that you search online for any similar project
proposals or published protocols using UKB data online, e.g. on OFS
registries, and check ongoing and previous projects here on Trello. You
also need to make sure that your project falls under the aim of the
overall SDCA UKB Application (See here: https://trello.com/c/INDKm9cV)

Move this card to 'Project proposals' here on Trello and either tag or
send an email to the people on the SDCA UKB RAP steering committee
(Daniel Witte, Christina Dahm, Alisa Kjærgaard, Luke Johnston or Daniel
Ibsen).

## 2. Get acceptance of the proposal from the organizing committee

*on Trello* Once the card has been added to 'Project proposal,' the
organizing committee will briefly discuss the project at one of our
regular meetings. This is mainly to make sure there is not a huge
overlap between other projects and to find potential for collaborations.
You may also get a few comments on things to consider in your project
and specific issues with the data you may need.

One from the organizing committee will be assigned to you as a contact
person. Because this person will contribute to your project, this person
will also be part of any publications from your UKB project.

## 3. Add project description to Trello under 'Ongoing projects'

*on Trello* After approval your project will be moved to 'Ongoing
projects' and you can add further details to your description if
necessary.

Add collaborators to your card and indicate in a comment on the card who
should have access to the data. Tag Luke and Alisa in your comment and
Luke will make the github repository for your project (add github user
IDs) and Alisa will register you at UKB and DNA Nexus (see here for
procedures: https://trello.com/c/p4uKUQRX)

## 4. Upload study protocol on osf.io and add link to project on Trello

*in R using UKB aid R package* We have decided that all projects should
include a pre-registered protocol of the study. This is to encourage
more open research and, because there are so many projects being
conducted in the UKB, to ensure that you can later claim to have been
first with the research idea, if necessary. This is also good research
practice and forces one to carefully think about the study before
conducting analyses.

In addition to the protocol, we encourage that most will also include a
detailed statistical analysis plan. This also makes it easier to perform
the analysis, as there is a clear direction from the beginning. The
analysis plan should be of a similar detail as how you would describe
your analysis in a manuscript.

Note that as an employee at the Region or Aarhus University you have
access to get your analysis plan reviewed by a statistician as part of
the [CONNECT
initiative](http://www.fagperson.auh.dk/afdelinger/connect-center-for-kliniske-genomiske-data/om-connect/).
If you are doing new or more complicated analyses, we encourage you to
use this offer.

The protocol can be written in R markdown using the template provided in
the ukbAid R package. At this point, you will download the [ukbAid R
package](https://github.com/steno-aarhus/ukbAid) on your own (local)
computer.

## 5. Statistical analyses completed

*in R on UKB RAP* At one point you will have conducted all your
analyses. We acknowledge that it is an iterative process, but at one
point you will be more or less done with the analysis part.

At SDCA we are working on establishing a "code cafe" where you can bring
your coding problems and we can review code together. This can be used
throughout your UKB analysis.

Before you save any results, tables or figures on Github and make the
public, you should consult with your contact person from the organizing
committee to make sure we follow the GDPR regulations. You are required
to be familiar with these before doing data analysis.

## 6. Get code analysis reviewed

*in R on Github* Once you have finished your analysis the organizing
committee will either themselves or find someone to review the code in
terms of its content, readability and whether it produces what you write
in your statistical analysis plan. This is to make sure there are no
major mistakes in the code.

## 7. Upload study manuscript to pre-print server and add link on Trello

*on Trello* Once you have a draft of the manuscript that is ready for
publication, this should be uploaded to a preprint server, again to
encourage more open science research practices. There can be reasons for
not doing this. Please state this in the project on Trello if that is
the case.

## 8. Add link to manuscript on Trello once published

*on Trello* Congratulations. Your study is published. Please upload the
link to the study on the project and move the project to 'Completed
project'

## 9, Data documentation

*in R on Github* As a final step, we would like you to add relevant code
to the common code files (note, this is under construction at the
moment). If you have made new variables, functions of types of analyses,
that could be of interest to everyone. This step is important because if
we all help build these documents, we can as a research unit be much
more efficient and aligned in our research practices. In the end, this
will be better use of research and give better prevention and care for
our patients.

Last updated: 8 September, 2022. DBI
